Support Py_GIL_DISABLED
Do not set py_limited_api when Py_GIL_DISABLED == 1, since it
will be rejected as shown:

  File "/usr/lib/python3.14t/site-packages/setuptools/_distutils/cmd.py", line 135, in ensure_finalized
    self.finalize_options()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 82, in finalize_options
  File "/usr/lib/python3.14t/site-packages/setuptools/command/bdist_wheel.py", line 250, in finalize_options
    self._validate_py_limited_api()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.14t/site-packages/setuptools/command/bdist_wheel.py", line 285, in _validate_py_limited_api
    raise ValueError(
    ...<4 lines>...
    )
ValueError: `py_limited_api='cp314'` not supported. `Py_LIMITED_API` is currently incompatible with `Py_GIL_DISABLED`.See https://github.com/python/cpython/issues/111506.